apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-pod
spec:
  containers:
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
    volumeMounts:
      - name: shared-root
        mountPath: /root
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud-slim
    command:
    - cat
    tty: true
    volumeMounts:
      - name: shared-root
        mountPath: /root
      - name: jenkins-secret
        mountPath: /secret
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-secret
        mountPath: /secret
  restartPolicy: Never
  volumes:
    - name: shared-root
      emptyDir: {}
    - name: jenkins-secret
      secret:
        secretName: jenkins-secret
  