apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deploy
  labels:
    app: petclinic
spec:
  containers:
  - name: petclinic
    image: gcr.io/cloudbees-public/bin-auth/petclinic:REPLACEME
    ports:
    - containerPort: 8080