apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: petclinic-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
        - name: petclinic
          image: gcr.io/cloudbees-public/bin-auth/petclinic:REPLACEME
          ports:
            - containerPort: 8080