apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/cloudbees-secret.json
    volumeMounts:
      - name: cloudbees-secret
        mountPath: /secret
  restartPolicy: Never
  volumes:
    - name: cloudbees-secret
      secret:
        secretName: cloudbees-secret