apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build-pod
spec:
  containers:
  - name: maven
    image: maven:3.5.0
    command:
    - cat
    tty: true
  - name: gcloud
    image: docker.io/beedemo/gcloud:gpg
    command:
    - cat
    tty: true
    volumeMounts:
      - name: shared-root
        mountPath: /root
      - name: cloudbees-secret
        mountPath: /secret
      - name: attestor-secret
        mountPath: /attestor
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/cloudbees-secret.json
    volumeMounts:
      - name: cloudbees-secret
        mountPath: /secret
  restartPolicy: Never
  volumes:
    - name: shared-root
      emptyDir: {}
    - name: cloudbees-secret
      secret:
        secretName: cloudbees-secret
    - name: attestor-secret
      secret:
        secretName: attestor-secret